<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-EHLHG19" failures="1" tests="4" name="tests.SignInTest" time="45.201" errors="0" timestamp="2022-06-07T17:24:06 CEST" skipped="0">
  <testcase classname="tests.SignInTest" name="successfulSignIn" time="20.194"/>
  <system-out/>
  <testcase classname="tests.SignInTest" name="signInWithInvalidSteamAccountNameAndValidPassword" time="8.228"/>
  <system-out/>
  <testcase classname="tests.SignInTest" name="signInWithValidSteamAccountNameAndInvalidPassword" time="8.817"/>
  <system-out/>
  <testcase classname="tests.SignInTest" name="signInWithInvalidCredentials" time="7.962">
    <failure message="Test unsuccessful, incorrect error message is displayed. Expected error message: The account name or password that you have entered is incorrect.. Actual error message displayed: Please verify your humanity by re-entering the characters in the captcha." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test unsuccessful, incorrect error message is displayed. Expected error message: The account name or password that you have entered is incorrect.. Actual error message displayed: Please verify your humanity by re-entering the characters in the captcha.
at tests.SignInTest.signInWithInvalidCredentials(SignInTest.java:146)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- signInWithInvalidCredentials -->
  <system-out/>
</testsuite> <!-- tests.SignInTest -->
